menu:
- {name: 'publications', url: '/publications'}
- {name: 'teaching', url: '/teaching'}
- {name: 'cv', url: '/cv'}
- {name: 'contact', url: '/contact'}

social:
- {icon: 'github', link: 'https://github.com/jbkamp'}
- {icon: 'twitter', link: 'https://x.com/jb_kamp'}
- {icon: 'linkedin', link: 'https://linkedin.com/in/jonathan-kamp'}

contacts:
- {name: 'Jonathan Kamp', role: 'PhD Candidate', department: 'Computational Linguistics and Text Mining Lab', institution: 'Vrije Universiteit Amsterdam', email: 'j.b.kamp~at~vu.nl', image: 'assets/img/cltl_logo.png'}

teachings:
- {name: 'Fairness in Data Science, course creator and instructor', institution: 'Vrije Universiteit Amsterdam', date: '2024', description: 'BSc Creative Technology (CreaTe)}
- {name: 'NLP Research Seminar, instructor', institution: 'Vrije Universiteit Amsterdam', date: 'September-October 2022', description: 'Research MA Human Language Technology'}
- {name: 'Computational Linguistics, teaching assistant', institution: 'Utrecht University', date: 'April-June 2019', description: 'BSc Artificial Intelligence'}
- {name: 'Taal en Computer <i>(Language and Computation)</i>, teaching assistant', institution: 'Utrecht University', date: 'February-April 2019', description: 'BA Linguistics'}
- {name: 'Digital Methods in Linguistics, teaching assistant', institution: 'Utrecht University', date: 'September-November 2018', description: 'Research MA Linguistics'}
- {name: 'Computational Linguistics, teaching assistant', institution: 'Utrecht University', date: 'April-June 2018', description: 'BSc Artificial Intelligence'}
