menu:
- {name: 'publications', url: '/publications'}
- {name: 'courses', url: '/courses'}
- {name: 'cv', url: '/cv'}
- {name: 'contact', url: '/contact'}

courses:
- {name: 'Vector Calculus', url: 'vector-calculus'}
- {name: 'Quantum Mechanics', url: 'quantum-mechanics'}
- {name: 'Stellar Structures', url: 'stellar-structures'}

social:
- {icon: 'github', link: 'https://github.com/jbkamp'}
- {icon: 'twitter', link: 'https://twitter.com/jb_kamp'}
- {icon: 'linkedin', link: 'https://linkedin.com/in/jonathan-kamp'}

contacts:
- {name: 'Jonathan Kamp', role: 'PhD Candidate', department: 'Computational Linguistics and Text Mining Lab', institution: 'Vrije Universiteit Amsterdam', email: 'j( dot )b( dot )kamp( at )vu( dot )nl', github: 'jbkamp', twitter: 'jb_kamp', linkedin: 'jonathan-kamp', image: 'assets/img/cltl_logo.png'}
